### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by kelligarcia88** [trevphil/preimage-attacks#43]
This project and readme is impressive! Wondering if you could consider adding either MIT, Apache 2.0, or GNU GPLv3? This would give users permissions to run the code locally, make modifications on their local machine, and if something is interesting is discovered, contribution a pull request upstream. Thanks for considering this issue!

**Comment by trevphil** [comment]
Hi @kelligarcia88, good point. I'm working on a major release to this codebase with a pip module and C++ backend (see branch `cpp`). Will add a license for this release.
